config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show;  end

  def edit;  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.delete
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: 'btn btn-info' %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit <%= @flat.name %></h1>
  <%= render 'form' %>
  <div class="footer">
    <ul>
      <li><%= link_to "Back", flats_path %></li>
   </ul>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All Flats!</h1>
  <%= link_to "Add", new_flat_path %>
    <div class="cards">
      <% @flats.each do |flat| %>
        <div class="card-product">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <div class="card-product-infos">
            <h2><%= link_to flat.name, flat_path(flat) %></h2>
            <p>Address: <%= flat.address %></p>
            <p>Price per night: <%= flat.price_per_night %></p>
            <p>Number of guests: <%= flat.number_of_guests %></p>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new apartment!</h1>
  <%= render "form" %>
  <div class="footer">
    <ul>
      <li><%= link_to "Back", flats_path %></li>
   </ul>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <div class="details">
      <p>Description: <%= @flat.description %></p>
      <p>Address: <%= @flat.address %></p>
      <p>Price per night: <%= @flat.price_per_night %></p>
      <p>Number of guests: <%= @flat.number_of_guests %></p>
    </div>
  <br>
    <div class="footer">
      <ul>
        <li><%= link_to "Back", flats_path %></li>
        <li><%= link_to "Edit", edit_flat_path %></li>
        <li><%= link_to "Delete", flat_path(@flat), method: :delete, data: { confirm: "Are you sure?" } %></li>
      </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>